services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
    networks:
      - cicd-practice

  backend:
    image: ioloolo/cicd-practice-backend:latest
    build: 
      context: backend
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    container_name: backend
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - cicd-practice

  frontend:
    image: ioloolo/cicd-practice-frontend:latest
    build: 
      context: frontend
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    container_name: frontend
    networks:
      - cicd-practice

  web:
    image: ioloolo/cicd-practice-web:latest
    build: 
      context: web
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    container_name: web
    depends_on:
      - frontend
      - backend
    links:
      - frontend
      - backend
    networks:
      - cicd-practice
    ports:
      - "80:80"

volumes:
  mongodb_data:

networks:
  cicd-practice:
