version: '3.8'

services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
    networks:
      - cicd-practice

  backend:
    image: ioloolo/cicd-practice-backend:latest
    build: backend
    container_name: backend
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - cicd-practice
    platforms:
      - "linux/amd64"
      - "linux/arm64"

  frontend:
    image: ioloolo/cicd-practice-frontend:latest
    build: frontend
    container_name: frontend
    networks:
      - cicd-practice
    platforms:
      - "linux/amd64"
      - "linux/arm64"

  web:
    image: ioloolo/cicd-practice-web:latest
    build: web
    container_name: web
    depends_on:
      - frontend
      - backend
    links:
      - frontend
      - backend
    networks:
      - cicd-practice
    ports:
      - "80:80"
    platforms:
      - "linux/amd64"
      - "linux/arm64"

volumes:
  mongodb_data:

networks:
  cicd-practice:
