version: '3.8'

services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb

  backend:
    image: ioloolo/cicd-practice-backend:latest
    build: backend
    container_name: backend
    depends_on:
      - mongodb
    links:
      - mongodb

  frontend:
    image: ioloolo/cicd-practice-frontend:latest
    build: frontend
    container_name: frontend

  web:
    image: ioloolo/cicd-practice-web:latest
    build: web
    container_name: web
    depends_on:
      - frontend
      - backend
    links:
      - frontend
      - backend
    ports:
      - "80:80"
