name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  # build-frontend:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout Repository
  #     uses: actions/checkout@v4
  #     with:
  #       submodules: recursive

  #   - name: Login to Docker Hub
  #     uses: docker/login-action@v3
  #     with:
  #       username: ${{ secrets.DOCKER_USERNAME }}
  #       password: ${{ secrets.DOCKER_PASSWORD }}

  #   - name: Setup Node.js
  #     uses: actions/setup-node@v4
  #     with:
  #       node-version: '20'

  #   - name: Install Frontend Dependencies
  #     run: |
  #       cd frontend
  #       yarn install

  #   - name: Build Frontend
  #     run: |
  #       cd frontend
  #       yarn build

  #   - name: Build and Push Frontend Docker images
  #     uses: docker/build-push-action@v6
  #     with:
  #       context: ./frontend
  #       push: true
  #       tags: ioloolo/cicd-practice-frontend:latest

  # build-backend:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout Repository
  #     uses: actions/checkout@v4
  #     with:
  #       submodules: recursive

  #   - name: Login to Docker Hub
  #     uses: docker/login-action@v3
  #     with:
  #       username: ${{ secrets.DOCKER_USERNAME }}
  #       password: ${{ secrets.DOCKER_PASSWORD }}

  #   - name: Set up JDK
  #     uses: actions/setup-java@v4
  #     with:
  #       distribution: 'adopt'
  #       java-version: '21'

  #   - name: Build backend
  #     run: |
  #       cd backend
  #       ./gradlew build
    
  #   - name: Build and Push Backend Docker images
  #     uses: docker/build-push-action@v6
  #     with:
  #       context: ./backend
  #       push: true
  #       tags: ioloolo/cicd-practice-backend:latest

  # build-web:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout Repository
  #     uses: actions/checkout@v4
  #     with:
  #       submodules: recursive

  #   - name: Login to Docker Hub
  #     uses: docker/login-action@v3
  #     with:
  #       username: ${{ secrets.DOCKER_USERNAME }}
  #       password: ${{ secrets.DOCKER_PASSWORD }}

  #   - name: Build and Push Web Docker images
  #     uses: docker/build-push-action@v6
  #     with:
  #       context: ./web
  #       push: true
  #       tags: ioloolo/cicd-practice-web:latest

  deploy:
    runs-on: ubuntu-latest
    # needs: [build-frontend, build-backend, build-web]

    steps:
    - name: SSH into server and deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        port: ${{ secrets.SERVER_PORT }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          printenv PATH
          cd ~/project
          git pull
          /usr/local/bin/docker-compose pull
          /usr/local/bin/docker-compose down
          /usr/local/bin/docker-compose up -d
