name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install frontend dependencies
      run: |
        cd frontend
        yarn install

    - name: Build frontend
      run: |
        cd frontend
        yarn build

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '21'

    - name: Build backend
      run: |
        cd backend
        ./gradlew build

    - name: Update apt package list
      run: sudo apt-get update

    - name: Install dependencies
      run: sudo apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common

    - name: Add Docker's official GPG key
      run: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

    - name: Set up Docker repository
      run: sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

    - name: Update apt package list again
      run: sudo apt-get update

    - name: Install Docker Engine
      run: sudo apt-get install -y docker-ce docker-ce-cli containerd.io

    - name: Verify Docker installation
      run: docker --version

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Set up Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.28.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
        docker-compose version

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images
      run: |
        docker-compose build
        docker image ls
        # docker-compose push

    - name: SSH into server and deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        port: ${{ secrets.SERVER_PORT }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd ~/project
          git pull origin master
          docker-compose down
          docker-compose pull
          docker-compose up -d
