name: Sync Submodules

on:
  push:
    branches:
      - main
    paths:
      - backend/**
      - frontend/**

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Update submodules
      run: |
        git submodule update --remote --merge
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git commit -am "Update submodules"
        git push origin master
